// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltttwatjtvnnkxmhxnoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0dHR3YXRqdHZubmt4bWh4bm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1OTE0MjUsImV4cCI6MjA2MjE2NzQyNX0.WKktobxAGGw0Gi39UQG43csKDaDwsELhj4N73zLd6wU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);